version: '3'
services:
  sqlserver:
    container_name: "sqlserver"
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD} # SET VALUE IN .env file (Use .env.test as reference)
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes: 
      - "./backups:/var/opt/mssql/backups"